language: java
jdk: oraclejdk8
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.m2
    

before_install:
- export APP_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate
  -Dexpression=project.version | grep -Ev '(^\[|Download\w+:)'`
- echo $APP_VERSION

install: "/bin/true"

script:
- mvn clean package -Pproduction -DskipTests=true

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$APP_VERSION-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for $GIT_TAG"
  - git push -q https://$GITHUBTOKEN@github.com/lgangloff/crossfit-2.0 --tags

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUBTOKEN
  file: target/crossfit-$GIT_TAG.jar
  on:
    repo: lgangloff/crossfit-2.0
    all_branches: true
    
