server:
    port: 8080

spring:
    liquibase:
        change-log: classpath:config/liquibase/master.xml
        contexts: production
    profiles:
        active: production
    datasource:
        driverClassName: org.postgresql.Driver        
        url: jdbc:postgresql://${POSTGRESQL_DB_HOST}:${POSTGRESQL_DB_PORT}/${POSTGRESQL_DB_NAME}
        username: ${POSTGRESQL_DB_USERNAME}
        password: ${POSTGRESQL_DB_PASSWORD}
        test-on-borrow: true
        test-on-return: true
        test-while-idle: true
        validation-query: SELECT 1;
        validation-interval: 30000
        remove-abandoned: true
        remove-abandoned-timeout: 60
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            default_schema: public
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.id.new_generator_mappings: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    jackson.serialization.fail-on-empty-beans: false
    messages:
        cache-seconds: 5000
        basename: i18n/messages
    thymeleaf:
        mode: XHTML
        cache: false
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
    mail:
        host: smtp.ionos.fr
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 64M

# security configuration (this key should be unique for your application, and kept secret)
security.rememberme.key: ${REMEMBER_ME_KEY}
security.access.card.token: ${CARD_API_KEY}
security.jwt.secret-key: ${JWT_KEY}

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
            
mail:
    sendgrid.api.key: ${SENDGRID_API_KEY}
    from: ne-pas-repondre@crossfit-nancy.fr
